### ISSUE TITLE
Manifest dependencies

### ISSUE THREAD

**Issue by eugenefine** [polywrap/technical-council#24]

**Comment by Niraj-Kamdar** [comment]
Here is a mock version of deps manifest that I come up with for polywrap monorepo 
```yaml
# web3api.deps.yaml
build:
  - name: coingecko
    uri: w3://fs/<path>/coingecko
  - name: covalent
    uri: w3://fs/<path>/covalent
  - name: etherscan
    uri: w3://ens/etherscan.eth
test:
  - name: coingecko
    uri: w3://fs/<path>/coingecko
  - name: covalent
    uri: w3://fs/<path>/covalent
  - name: etherscan
    uri: w3://ipfs/QmHash..
  
```
